### ISSUE TITLE
When postal code is not found to_region method returns entire hash of postal codes and regions

### ISSUE THREAD

**Issue by serv** [jgv/area#4]
If you use "9888" as the postal code, and do `to_region` on it, you get the entire hash of regions.

I don't think this is useful. It would make more sense to return `[]` so that we can check that the the postal code is invalid.

**Comment by jgv** [comment]
In this instance would you expect #to_region to return an empty array or to return nil?

**Comment by serv** [comment]
I think either should be fine. Either one of them would be a better indication that the postal code is not valid.

**Comment by jgv** [comment]
True. Alternatively it could throw a not found error.
