### ISSUE TITLE
How often is the zipcode data refreshed?

### ISSUE THREAD

**Issue by mkirchstein** [jgv/area#8]
I was just curious how often the source data is refreshed. I've read that the USPS updates zipcode mappings on a monthly basis, but I'd be happy a refresh just 3-4 times a year. 

Also, would the gem's version get bumped if there were no code changes but new data loaded? If so, I think I'd opt to not fixing this gem's version in my Gemfile. A tad more transparency on this issue in the docs would be great.

Overall, though, thank you very much for such an easy to use gem!

**Comment by jgv** [comment]
Thanks Matt. I'd bump the minor version number if there was a change. I'd consider that a "catergory two change" per the RubyGems docs (http://docs.rubygems.org/read/chapter/7). 

The next change to this gem will be updating the data to be of a higher quality. Hopefully I'll be able to address this by the end of the month. If its of any interest, I'm considering modifying and using a version of the data found here http://federalgovernmentzipcodes.us/

How do you envision the docs changing? Making mention of my versioning strategy?

**Comment by mkirchstein** [comment]
Or even just a mention of when the source data was last updated in the readme would be great. Also, now that I know  that the zip info is loaded from /data/zipcodes.csv file I can just look it's last commit date too.

Thanks again for a great gem.

**Comment by jgv** [comment]
Thank you!
